env: "prod"
connection_string: "postgres://postgres:admin@localhost:5432/url-shortener?sslmode=disable"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s

clients:
  sso:
    address: "localhost:44044"
    timeout: 4s
    retries_count: 3

app_secret: "top_secret"